### ISSUE TITLE
Landscapes dataset

### ISSUE THREAD

**Issue by CKchaos** [manicman1999/StyleGAN-Tensorflow-2.0#1]
Hi, thanks for sharing your work.
I'm curious about where you get the dataset since I can't find one landscape dataset as large as 3.2 million images.

**Comment by manicman1999** [comment]
Hi! I should clarify that 3.2 million images is how many images is shown to the Discriminator, not the actual number of images in my dataset. My dataset consists of only ~14000 landscape images, scraped from reddit.com/r/EarthPorn. Thus, of those 3.2 million images, many are repeats of previously shown images.

**Comment by CKchaos** [comment]
Thanks for the clarification. It does address my problem.
